airboltic:
  target: dev
  outputs:
    dev:
      type: postgres
      host: <HOST>
      user: <USER>
      password: <PASSWORD>
      port: <PORT>
      dbname: postgres
      schema: <SCHEMA>
      keepalives_idle: 0
      connect_timeout: 10 # default 10 seconds
      retries: 1